
---
  - name: playbook
    hosts: R3
    gather_facts: false
    connection: local
    tasks:
# Configuring OSPF Routing Protocol version 4
      - name: OSPF Routing protocol version 4
        ios_config:
          commands:
            - router ospf 200
            - router-id 3.3.3.3
            - network 192.168.5.0 0.0.0.255 area 0
            - network 192.168.4.0 0.0.0.3 area 0
            - default-information originate
            - do write
# Configuring OSPF Routing Protocol version 6
      - name: OSPF Routing protocol version 6
        ios_config:
          commands:
            - ipv6 unicast-routing 
            - ipv6 router ospf 200
#            - router-id 3.3.3.3
            - interface fastethernet 0/0
            - ipv6 ospf 200 area 0
            - interface loopback 0
            - ipv6 ospf 200 area 0
            - do write
 

