---
  - name: playbook
    hosts: R3
    gather_facts: false
    connection: local
    tasks:
# Configuring BGP Routing Protocol version 4
#      - name: BGP Routing protocol version 4
#        ios_config:
#          commands:
#            - router bgp 65000
#            - bgp router-id 3.3.3.3
#            - neighbor 192.168.77.1 remote-as 65100
#            - network 192.168.5.0 mask 255.255.255.0
# Configuring BGP redistribution into OSPF
      - name: Redistribute BGP to OSPF 
        ios_config:
          commands:
            - router ospf 200
            - redistribute bgp 65000 subnets
            - do write

