
---
  - name: playbook
    hosts: R2
    gather_facts: false
    connection: local
    tasks:
# Configuring EIGRP Routing Protocol version 4
      - name: EIGRP Routing protocol version 4
        ios_config:
          commands:
            - ip routing
            - router eigrp 100
            - redistribute ospf 200 metric 1500 1 255 10 1500 
            - do write
# Configuring EIGRP Routing Protocol version 6
#      - name: EIGRP Routing protocol version 6
#        ios_config:
#          commands:
#            - ipv6 router eigrp 100
#            - redistribute ospf 200 metric 1500 1 255 10 1500
     

