
---
  - name: playbook
    hosts: R1
    gather_facts: false
    connection: local
    tasks:
      - name: Change Hostname
        ios_command:
          commands:
            - configure terminal 
            - hostname {{inventory_hostname}}
