
---
  - name: playbook
    hosts: R1
    gather_facts: false
    connection: local
    tasks:
      - name: Configure IPv6
        ios_config:
          commands:
            - ipv6 unicast-routing
      - name: Assign IP address version 4 & 6
        ios_config:
          commands:
# Assign IPv4, v6 & link-local on interface loopback 0
            - interface loopback0
            - ip address 192.168.6.1 255.255.255.0
            - ipv6 address 2001:db8:cafe:6::1/64
            - ipv6 address fe80::1 link-local

# Assign IPv4, v6 & link-local on interface fastethernet 0/0
            - interface fastEthernet 0/0
            - ipv6 address 2001:db8:cafe:1::1/64
            - ipv6 address fe80::1 link-local

# Assign IPv4, v6 & link-local on interface fastethernet 0/1
            - interface fastEthernet 1/0
            - no shutdown
            - ip address 192.168.2.1 255.255.255.252
            - ipv6 address fe80::1 link-local            
            - ipv6 address 2001:db8:cafe:2::1/64
